### ISSUE TITLE
There is a additional line when is just one child

### ISSUE THREAD

**Issue by rodoo9** [zikosichi/hierarchy-view#4]
There is a additional line when is just one child as you can see in this example

![image](https://user-images.githubusercontent.com/25985734/29118773-b0c9d514-7d03-11e7-9985-3b8d6ea381eb.png)

**Comment by mikaint** [comment]
+1

**Comment by FrancYescO** [comment]
someone found a fix?

**Comment by kalilmaciel** [comment]
Hi, I found a fix.

Put this on file hierachy-view.scss on line 68.

&:only-child:after{
          width: 0;
        }

it will work.

**Comment by FrancYescO** [comment]
@kalilmaciel i already put the fix in PR

**Comment by zsichinava** [comment]
Thanks, @FrancYescO for PR. Will review and merge
